#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend myfrontend
    bind *:80
    mode http
    default_backend b_servers

backend b_servers
    balance roundrobin
    server 71225-web-01 100.26.226.249:80 check
    server 71225-web-02	18.206.233.70:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
