#!/usr/bin/env bash
# A script that displays Best school 10x
# 9th iteration displays Best school then hi

x=0
while (( x<10 ))
do
	x=$(( x=x+1 ))

	if (( x!=9 ))
	then
		echo Best School

	elif (( x==9 ))
	then
		echo Hi
	fi
done
