#!/usr/bin/env bash
# A script that displays Best school 10x
# 9th iteration displays Best school then hi

x=0
while (( x<10 ))
do
	if (( x!=8 ))
	then
		echo Best School
	fi

	if (( x==8 ))
	then
		echo Hi
	fi
	x=$(( x=x+1 ))
done
